apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: georgi1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ngin:1.12
          ports:
            - containerPort: 80
